/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryItemType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
  'analytic' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participants' : IDL.Vec(IDL.Principal),
  'messages' : IDL.Vec(Message),
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'timestamp' : IDL.Int,
  'itemType' : GalleryItemType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [GalleryItemType, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([IDL.Vec(IDL.Principal)], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getGalleryByType' : IDL.Func(
      [IDL.Opt(GalleryItemType)],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryItemType = IDL.Variant({
    'video' : IDL.Null,
    'photo' : IDL.Null,
    'analytic' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participants' : IDL.Vec(IDL.Principal),
    'messages' : IDL.Vec(Message),
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'timestamp' : IDL.Int,
    'itemType' : GalleryItemType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [GalleryItemType, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([IDL.Vec(IDL.Principal)], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getGalleryByType' : IDL.Func(
        [IDL.Opt(GalleryItemType)],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };